#!/bin/bash
# ============================================================================
# Unity Follower Interface ???單
# 
# 雿輻?孵?嚗?#   cd ~/ros2_ws/scripts
#   ./start_follower.sh
#
# 瘜冽?嚗??賢??銵?ros2 launch openarm_bringup openarm.bimanual.launch.py
# ============================================================================

set -e

# 閮剖? DISPLAY ?啣?霈 (nvarguscamerasrc ?閬?
export DISPLAY=:0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROS2_WS="$SCRIPT_DIR/.."
VENV_PATH="/home/idaka/openarm_can/python/venv"

echo "=============================================="
echo "Unity Follower Interface - 500Hz MIT Control"
echo "=============================================="

# 0. 皜?畾?蝔?
echo ""
echo "[Step 0] Cleaning up residual processes..."
PROCS_TO_KILL="ros_tcp_endpoint|unity_interface_follower|camera_publisher"
KILLED=0
for proc in ros_tcp_endpoint unity_interface_follower camera_publisher; do
    if pkill -f "$proc" 2>/dev/null; then
        echo "  Killed residual: $proc"
        KILLED=$((KILLED + 1))
    fi
done
if [ $KILLED -eq 0 ]; then
    echo "  No residual processes found."
else
    echo "  Killed $KILLED process(es). Waiting 1s..."
    sleep 1
fi

# 1. 閮剔蔭 CAN
echo ""
echo "[Step 1] Setting up CAN interfaces..."
"$SCRIPT_DIR/cansetup.sh"

# 霈??CAN mapping
source /tmp/can_arm_map 2>/dev/null || { RIGHT_CAN=can1; LEFT_CAN=can2; }

# 撽? CAN 隞撠梁?
CAN_OK=false
if ip link show "$RIGHT_CAN" 2>/dev/null | grep -q "UP" && \
   ip link show "$LEFT_CAN" 2>/dev/null | grep -q "UP"; then
    echo "  ??$RIGHT_CAN and $LEFT_CAN are UP"
    CAN_OK=true
fi

# 憒? CAN 瘝絲靘??岫 --reset ??
if [ "$CAN_OK" = false ]; then
    echo "  ?? CAN interfaces not ready, trying USB hub reset..."
    "$SCRIPT_DIR/cansetup.sh" --reset
    source /tmp/can_arm_map 2>/dev/null || { RIGHT_CAN=can1; LEFT_CAN=can2; }
    sleep 1
    if ip link show "$RIGHT_CAN" 2>/dev/null | grep -q "UP" && \
       ip link show "$LEFT_CAN" 2>/dev/null | grep -q "UP"; then
        echo "  ??$RIGHT_CAN and $LEFT_CAN are UP (after reset)"
    else
        echo "  ??CAN interfaces still not ready after reset."
        echo "     Please check PCAN USB connections and try again."
        exit 1
    fi
fi

# 2. 霈??收??蝵?+ ?亙熒瑼Ｘ
echo ""
echo "[Step 2] Reading current motor positions..."

SEND_IDS=(001 002 003 004 005 006 007)
RECV_IDS=(011 012 013 014 015 016 017)
JOINT_NAMES=(J1 J2 J3 J4 J5 J6 J7)
P_MAX=12.5
INIT_FILE="/tmp/initial_joint_positions"

# 皜征?怠?瑼?echo "# Generated by start_follower.sh Step 2" > "$INIT_FILE"
echo "# Format: side joint_index angle_rad" >> "$INIT_FILE"

MISSING_COUNT=0
MISSING_LIST=""

for SIDE in RIGHT LEFT; do
    if [ "$SIDE" = "RIGHT" ]; then BUS=$RIGHT_CAN; else BUS=$LEFT_CAN; fi

    # candump嚗??recv_id (0x11~0x17)嚗?瞈暹? echo
    TMPFILE=$(mktemp /tmp/can_read_XXXXXX.txt)
    candump "$BUS",011:7FF,012:7FF,013:7FF,014:7FF,015:7FF,016:7FF,017:7FF -t a -n 7 > "$TMPFILE" 2>&1 &
    DUMP_PID=$!
    sleep 0.1

    # ?潮?enable (0xFC) 霈????    for sid in "${SEND_IDS[@]}"; do
        cansend "$BUS" "${sid}#FFFFFFFFFFFFFFFC"
        sleep 0.01
    done

    # 蝑???嚗?憭?2 蝘?
    for i in $(seq 1 20); do
        COUNT=$(wc -l < "$TMPFILE" 2>/dev/null || echo 0)
        [ "$COUNT" -ge 7 ] && break
        sleep 0.1
    done
    kill $DUMP_PID 2>/dev/null
    wait $DUMP_PID 2>/dev/null

    # 瑼Ｘ瘥?擐祇??臬?
    for idx in 0 1 2 3 4 5 6; do
        RECV_ID="${RECV_IDS[$idx]}"
        LINE=$(grep " ${RECV_ID} " "$TMPFILE" 2>/dev/null || true)

        if [ -z "$LINE" ]; then
            echo "  ERROR: $SIDE ${JOINT_NAMES[$idx]} (CAN ID ${SEND_IDS[$idx]}) on $BUS ??no response!"
            MISSING_COUNT=$((MISSING_COUNT + 1))
            MISSING_LIST="$MISSING_LIST  - $SIDE ${JOINT_NAMES[$idx]} (${SEND_IDS[$idx]}) on $BUS\n"
            echo "$SIDE $idx 0.0" >> "$INIT_FILE"
        else
            # 閫?Ⅳ position: data[1]<<8 | data[2]
            HEX_BYTES=$(echo "$LINE" | sed 's/.*\[8\]//' | tr -d ' ')
            B1=${HEX_BYTES:2:2}
            B2=${HEX_BYTES:4:2}
            Q_UINT=$((16#${B1}${B2}))
            ANGLE_RAD=$(awk "BEGIN {printf \"%.4f\", $Q_UINT / 65535.0 * 2.0 * $P_MAX - $P_MAX}")
            ANGLE_DEG=$(awk "BEGIN {printf \"%.2f\", $ANGLE_RAD * 180.0 / 3.14159265}")
            echo "  $SIDE ${JOINT_NAMES[$idx]}: ${ANGLE_RAD} rad (${ANGLE_DEG} deg)"
            echo "$SIDE $idx $ANGLE_RAD" >> "$INIT_FILE"
        fi
    done

    rm -f "$TMPFILE"
done

# ?亙熒瑼Ｘ蝯?
if [ $MISSING_COUNT -gt 0 ]; then
    echo ""
    echo "??  $MISSING_COUNT motor(s) did not respond:"
    echo -e "$MISSING_LIST"
    read -rp "Continue anyway? (y/N) " ANSWER
    if [ "$ANSWER" != "y" ] && [ "$ANSWER" != "Y" ]; then
        echo "Aborted."
        exit 1
    fi
    echo "Continuing with missing motors set to 0.0 rad..."
else
    echo ""
    echo "??All 14 motors responded."
fi

echo "Saved to $INIT_FILE"

# 3. Source ROS2
echo ""
echo "[Step 3] Sourcing ROS2..."
source /opt/ros/humble/setup.bash
source "$ROS2_WS/install/setup.bash" 2>/dev/null || true

# 4. ?? ROS TCP Endpoint (??瑁?)
echo ""
echo "[Step 4] Starting ROS TCP Endpoint..."
ros2 run ros_tcp_endpoint default_server_endpoint --ros-args -p ROS_IP:=0.0.0.0 &
TCP_PID=$!
echo "TCP Endpoint PID: $TCP_PID"

# 5. 蝑? TCP Endpoint ??
sleep 2

# 6. ?? Camera Publisher (??瑁?嚗蝙?函頂蝯?Python 隞交??GStreamer)
# 敹??典???venv 銋??瑁?嚗???venv ??OpenCV ?航瘝? GStreamer ?舀
echo ""
echo "[Step 6] Starting Camera Publisher (background)..."
python3 "$ROS2_WS/src/openarm_ros2/openarm_bringup/scripts/camera_publisher.py" \
    --ros-args -p use_test_pattern:=false -p jpeg_quality:=50 &
CAMERA_PID=$!
echo "Camera Publisher PID: $CAMERA_PID"

# 蝑??豢?????sleep 2

# 7. ???啣? (?? unity_interface_follower 雿輻)
echo ""
echo "[Step 7] Activating virtual environment: $VENV_PATH"
source "$VENV_PATH/bin/activate"

# 8. ?? Unity Follower Interface (??瑁?)
echo ""
echo "[Step 8] Starting Unity Follower Interface..."
echo ""
python3 "$ROS2_WS/src/openarm_ros2/openarm_bringup/scripts/unity_interface_follower.py"

# 皜?
echo ""
echo "Shutting down..."
deactivate 2>/dev/null || true
kill $CAMERA_PID 2>/dev/null || true
kill $TCP_PID 2>/dev/null || true
echo "Shutdown complete."
