#!/bin/bash
# ============================================================================
# Unity Follower Interface 啟動腳本
# 
# 使用方式：
#   cd ~/ros2_ws/scripts
#   ./start_follower.sh
#
# 注意：不能同時執行 ros2 launch openarm_bringup openarm.bimanual.launch.py
# ============================================================================

set -e

# 設定 DISPLAY 環境變數 (nvarguscamerasrc 需要)
export DISPLAY=:0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROS2_WS="$SCRIPT_DIR/.."
VENV_PATH="/home/idaka/openarm_can/python/venv"

echo "=============================================="
echo "Unity Follower Interface - 500Hz MIT Control"
echo "=============================================="

# 0. 清理殘留程序
echo ""
echo "[Step 0] Cleaning up residual processes..."
PROCS_TO_KILL="ros_tcp_endpoint|unity_interface_follower|camera_publisher"
KILLED=0
for proc in ros_tcp_endpoint unity_interface_follower camera_publisher; do
    if pkill -f "$proc" 2>/dev/null; then
        echo "  Killed residual: $proc"
        KILLED=$((KILLED + 1))
    fi
done
if [ $KILLED -eq 0 ]; then
    echo "  No residual processes found."
else
    echo "  Killed $KILLED process(es). Waiting 1s..."
    sleep 1
fi

# 1. 設置 CAN
echo ""
echo "[Step 1] Setting up CAN interfaces..."
"$SCRIPT_DIR/cansetup.sh"

# 讀取 CAN mapping
source /tmp/can_arm_map 2>/dev/null || { RIGHT_CAN=can1; LEFT_CAN=can2; }

# 驗證 CAN 介面就緒
CAN_OK=false
if ip link show "$RIGHT_CAN" 2>/dev/null | grep -q "UP" && \
   ip link show "$LEFT_CAN" 2>/dev/null | grep -q "UP"; then
    echo "  ✅ $RIGHT_CAN and $LEFT_CAN are UP"
    CAN_OK=true
fi

# 如果 CAN 沒起來，嘗試 --reset 重來
if [ "$CAN_OK" = false ]; then
    echo "  ⚠️ CAN interfaces not ready, trying USB hub reset..."
    "$SCRIPT_DIR/cansetup.sh" --reset
    source /tmp/can_arm_map 2>/dev/null || { RIGHT_CAN=can1; LEFT_CAN=can2; }
    sleep 1
    if ip link show "$RIGHT_CAN" 2>/dev/null | grep -q "UP" && \
       ip link show "$LEFT_CAN" 2>/dev/null | grep -q "UP"; then
        echo "  ✅ $RIGHT_CAN and $LEFT_CAN are UP (after reset)"
    else
        echo "  ❌ CAN interfaces still not ready after reset."
        echo "     Please check PCAN USB connections and try again."
        exit 1
    fi
fi

# 2. 讀取目前馬達位置 + 健康檢查
#    暫時關閉 set -e，因為 candump/kill/wait 可能回傳非零
set +e
echo ""
echo "[Step 2] Reading current motor positions..."

SEND_IDS=(001 002 003 004 005 006 007)
RECV_IDS=(011 012 013 014 015 016 017)
JOINT_NAMES=(J1 J2 J3 J4 J5 J6 J7)
P_MAX=12.5
INIT_FILE="/tmp/initial_joint_positions"

# 清空暫存檔
echo "# Generated by start_follower.sh Step 2" > "$INIT_FILE"
echo "# Format: side joint_index angle_rad" >> "$INIT_FILE"

MISSING_COUNT=0
MISSING_LIST=""

for SIDE in RIGHT LEFT; do
    if [ "$SIDE" = "RIGHT" ]; then BUS=$RIGHT_CAN; else BUS=$LEFT_CAN; fi

    # candump：只聽 recv_id (0x11~0x17)，過濾掉 echo（-n 7 收滿自動退出）
    TMPFILE=$(mktemp /tmp/can_read_XXXXXX.txt)
    candump "$BUS",011:7FF,012:7FF,013:7FF,014:7FF,015:7FF,016:7FF,017:7FF -t a -n 7 > "$TMPFILE" 2>&1 &
    DUMP_PID=$!
    sleep 0.1

    # 發送 enable (0xFC) 讀取狀態
    for sid in "${SEND_IDS[@]}"; do
        cansend "$BUS" "${sid}#FFFFFFFFFFFFFFFC" 2>/dev/null
        sleep 0.01
    done

    # 等待回應（最多 2 秒）
    for i in $(seq 1 20); do
        COUNT=$(wc -l < "$TMPFILE" 2>/dev/null || echo 0)
        [ "$COUNT" -ge 7 ] && break
        sleep 0.1
    done
    kill $DUMP_PID 2>/dev/null || true
    wait $DUMP_PID 2>/dev/null || true

    # 檢查每顆馬達是否回傳
    for idx in 0 1 2 3 4 5 6; do
        RECV_ID="${RECV_IDS[$idx]}"
        LINE=$(grep " ${RECV_ID} " "$TMPFILE" 2>/dev/null || true)

        if [ -z "$LINE" ]; then
            echo "  ERROR: $SIDE ${JOINT_NAMES[$idx]} (CAN ID ${SEND_IDS[$idx]}) on $BUS — no response!"
            MISSING_COUNT=$((MISSING_COUNT + 1))
            MISSING_LIST="$MISSING_LIST  - $SIDE ${JOINT_NAMES[$idx]} (${SEND_IDS[$idx]}) on $BUS\n"
            echo "$SIDE $idx 0.0" >> "$INIT_FILE"
        else
            # 解碼 position: data[1]<<8 | data[2]
            HEX_BYTES=$(echo "$LINE" | sed 's/.*\[8\]//' | tr -d ' ')
            B1=${HEX_BYTES:2:2}
            B2=${HEX_BYTES:4:2}
            Q_UINT=$((16#${B1}${B2}))
            ANGLE_RAD=$(awk "BEGIN {printf \"%.4f\", $Q_UINT / 65535.0 * 2.0 * $P_MAX - $P_MAX}")
            ANGLE_DEG=$(awk "BEGIN {printf \"%.2f\", $ANGLE_RAD * 180.0 / 3.14159265}")
            echo "  $SIDE ${JOINT_NAMES[$idx]}: ${ANGLE_RAD} rad (${ANGLE_DEG} deg)"
            echo "$SIDE $idx $ANGLE_RAD" >> "$INIT_FILE"
        fi
    done

    rm -f "$TMPFILE"
done

# 健康檢查結果
if [ $MISSING_COUNT -gt 0 ]; then
    echo ""
    echo "⚠️  $MISSING_COUNT motor(s) did not respond:"
    echo -e "$MISSING_LIST"
    read -rp "Continue anyway? (y/N) " ANSWER
    if [ "$ANSWER" != "y" ] && [ "$ANSWER" != "Y" ]; then
        echo "Aborted."
        exit 1
    fi
    echo "Continuing with missing motors set to 0.0 rad..."
else
    echo ""
    echo "✅ All 14 motors responded."
fi

echo "Saved to $INIT_FILE"

# 恢復 set -e
set -e

# 3. Source ROS2
echo ""
echo "[Step 3] Sourcing ROS2..."
source /opt/ros/humble/setup.bash
source "$ROS2_WS/install/setup.bash" 2>/dev/null || true

# 4. 啟動 ROS TCP Endpoint (背景執行)
echo ""
echo "[Step 4] Starting ROS TCP Endpoint..."
ros2 run ros_tcp_endpoint default_server_endpoint --ros-args -p ROS_IP:=0.0.0.0 &
TCP_PID=$!
echo "TCP Endpoint PID: $TCP_PID"

# 5. 等待 TCP Endpoint 啟動
sleep 2

# 6. 啟動 Camera Publisher (背景執行，使用系統 Python 以支援 GStreamer)
# 必須在啟用 venv 之前執行，因為 venv 的 OpenCV 可能沒有 GStreamer 支援
echo ""
echo "[Step 6] Starting Camera Publisher (background)..."
python3 "$ROS2_WS/src/openarm_ros2/openarm_bringup/scripts/camera_publisher.py" \
    --ros-args -p use_test_pattern:=false -p jpeg_quality:=50 &
CAMERA_PID=$!
echo "Camera Publisher PID: $CAMERA_PID"

# 等待相機初始化
sleep 2

# 7. 啟用虛擬環境 (僅供 unity_interface_follower 使用)
echo ""
echo "[Step 7] Activating virtual environment: $VENV_PATH"
source "$VENV_PATH/bin/activate"

# 8. 啟動 Unity Follower Interface (前景執行)
echo ""
echo "[Step 8] Starting Unity Follower Interface..."
echo ""
python3 "$ROS2_WS/src/openarm_ros2/openarm_bringup/scripts/unity_interface_follower.py"

# 清理
echo ""
echo "Shutting down..."
deactivate 2>/dev/null || true
kill $CAMERA_PID 2>/dev/null || true
kill $TCP_PID 2>/dev/null || true
echo "Shutdown complete."
