;###
;###DLL日志
;###
[DEVTRACE]

;###
;###公共路径
;###
Path=C:\canfd-net-tool-log\

;###
;###文件打开方式
;###
OpenMode=a+

;###
;###日志保留天数
;###
FileDay=31

;###
;###是否加密
;###
Encrypt=0

;###
;###日志开关
;###
Switch=1

;###
;###日志级别
;###级别从低到高依次是：DEBUG INFO WARN ERROR FATAL
;###
Level=INFO

